### ISSUE TITLE
Add user to `input` group

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/meta-srobo#2]
Similar to #1, if people are doing their own USB control, they'll need permissions to access the devices.

> serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'

This likely involves adding the running user to the `input` group (Although that'll need confirming).

**Comment by trickeydan** [comment]
The `input` group is for touchscreen and pointer control. I suspect we want `dialout`
