### ISSUE TITLE
RFC: Merge this repo into robot-image

### ISSUE THREAD

**Issue by trickeydan** [srobo/meta-srobo#25]
I would like to suggest that we merge this repo into the [robot-image](https://github.com/srobo/robot-image) repo.

**Pros**

- Easier to develop our image, we don't have to bump in two places
- Easier for new volunteers to find our recipes etc.
- One place for our OS build
- Submodules are for external deps only (i.e poky etc.)

**Cons**

- It's slightly more difficult for other people to use our recipes. We don't know of anybody doing this anyway and are under no obligations to support them if they want to.

@WillB97 @8BitJosh @raccube @Tyler-Ward @RealOrangeOne I'd like to hear your thoughts please!

**Comment by 8BitJosh** [comment]
I agree with merging these repos,  it brings all the image build bits into a single repo making it easier to manage.  I think our image is unique enough that it is unlikely that someone would want to use our recepies anyway.

**Comment by trickeydan** [comment]
@raccube has also given approval of this, and I'm interpreting Will's thumbs up as approval too, so I'm going to go ahead and do this now.
