### ISSUE TITLE
Update recipes for Early Feb 2022 Release

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/meta-srobo#9]
@trickeydan can you list the recipes that need updating here

**Comment by trickeydan** [comment]
- Zoloto - 0.8.0
- j5-zoloto - 0.2.0
- sr.robot3 -2022.1.0

**Comment by Tyler-Ward** [comment]
https://github.com/srobo/meta-srobo/pull/11 covers zoloto updates
https://github.com/srobo/meta-srobo/pull/10 covers the sr.robot update

**Comment by trickeydan** [comment]
Astoria has now been updated in #13  and #12
